In [3]:
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [5]:
import sklearn 

In [7]:
from sklearn.cluster import KMeans

In [8]:
df = KMeans(n_clusters=2,random_state=1)

In [9]:
df

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=1, tol=0.0001, verbose=0)

In [14]:
c=df.fit(X)
c

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=1, tol=0.0001, verbose=0)

In [15]:
c.labels_

array([0, 0, 0, 1, 1, 1])

In [18]:
c.predict([[0,0]])

array([0])

In [19]:
c.cluster_centers_

array([[  1.,   2.],
       [ 10.,   2.]])